swagger: "2.0"
info:
  title: Cast and Crew API
  description: These APIs are to be used to fetch the Cast and Crew Rail on Single Content and Series Content Details Page
  version: 1.0.0
host: api.example.com
schemes:
  - https
  - http
paths:
  /rest/api/v1/cast/{id}:
    get:
      summary: Get cast and crew details.
      description: Returns the list of the cast and crew members of that content based on the content id and irrespective of content type.
      produces:
        - application/json
      parameters:
        - name: "id"
          in: "path"
          description: "ID of the content"
          required: true
          type: "string"
      responses:
        200:
          description: OK
          schema:
            type: "object"
            properties:
              code:
                type: "string"
                example: "200"
              message:
                type: "string"
                example: "OK"
              data:
                type: "object"
                properties:
                  totalCount:
                    type: "integer"
                    example: "1"
                  castList:
                    type: "array"
                    items:
                      $ref: "#/definitions/CastAndCrewMember"

        400:
          description: "Invalid content id"
        404:
          description: "No cast and crew details found for this content ID"
        401:
          description: "Unauthorized"
definitions:
  CastAndCrewMember:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
        example:
          "2314nsdfspf123na-nadabfabobad21e"
      name:
        type: "string"
        example:
          "Daniel Radcliffe"
      characterDetails:
        type: "object"
        properties:
          name:
            type: "string"
            example:
              "Harry Potter"
            description: "Daniel Radcliffe played the role of a wizard."
      role:
        type: "string"
        example:
          "Lead Actor"
        default: "null"
      type:
        type: "string"
        enum:
          - "CAST"
          - "CREW"
        default: "CAST"
        example: "CAST"
      images:
        properties:
          type:
            type: "string"
            example: "THUMBNAIL"
          small:
            type: "string"
            example: "https://imageservice.utvx.eu/v1/images/persons/2314nsdfspf123na-nadabfabobad21e/small.png"
          medium:
            type: "string"
            example: "https://imageservice.utvx.eu/v1/images/persons/2314nsdfspf123na-nadabfabobad21e/medium.png"
          large:
            type: "string"
            example: "https://imageservice.utvx.eu/v1/images/persons/2314nsdfspf123na-nadabfabobad21e/large.png"
    xml:
      name: "Cast and Crew Member"